package com.lox;


/* This class is generated by com.lox.tool.AstGenerator */
abstract class Expression {
   static class Binary extends Expression {
      private final Expression left;
      private final Token token;
      private final Expression right;

      Binary(Expression left, Token token, Expression right) {
         this.left = left;
         this.token = token;
         this.right = right;
      }
   }

   static class Grouping extends Expression {
      private final Expression expression;

      Grouping(Expression expression) {
         this.expression = expression;
      }
   }

   static class Literal extends Expression {
      private final Object value;

      Literal(Object value) {
         this.value = value;
      }
   }

   static class Unary extends Expression {
      private final Token operator;
      private final Expression right;

      Unary(Token operator, Expression right) {
         this.operator = operator;
         this.right = right;
      }
   }

}
